# Brute Force Detection
THRESHOLD = 3
WINDOW_MINUTES = 5

# Password Spraying Detection
SPRAY_THRESHOLD = 3
SPRAY_WINDOW_MINUTES = 10

# Impossible Travel Detection
TRAVEL_THRESHOLD = 2
TRAVEL_WINDOW_MINUTES = 5

# Risk Scoring
SUSPICIOUS_COUNTRIES = ["RU", "CN", "KP"]
FAILED_LOGIN_WEIGHT = 3
SUSPICIOUS_COUNTRY_SCORE = 5
TOR_SCORE = 5
SPRAY_USER_WEIGHT = 2
TRAVEL_IP_WEIGHT = 2

# Severity Thresholds
SEVERITY_HIGH = 12
SEVERITY_MEDIUM = 6